FROM ubuntu
  
MAINTAINER wimness@163.com
 
RUN apt-get update && apt-get install -y python python-pip python-dev

RUN pip install --upgrade pip

RUN pip install --trusted-host pypi.python.org -r requirements.txt


