version: '2'
services:
 spider:
  build: ./spider/
  depends_on:
   - db
    
 db:
  build: ./db/
  volumes:
   - ../pgd:/var/lib/postgresql/data
  ports:
   - 54322:5432
  environment:
   POSTGRES_PASSWORD: wimness
   
#  web:
#   build: ./web/
#   ports:
#    - 8088:8080

   
