version: '2'
services:
 spider:
  image: xdlkc/spider
  depends_on:
   - db
    
 db:
  image: xdlkc/sql
  volumes:
   - ../pgd:/var/lib/postgresql/data
  ports:
   - 54322:5432
  environment:
   POSTGRES_PASSWORD: wimness
   
#  web:
#   image: xdlkc/web
#   ports:
#    - 8088:8080

   
