version: '2'
services:
#  spider:
#   build: ./spider/
#   depends_on:
#    - db
    
 db:
  image: lkc_db
  volumes:
   - ../pgd:/var/lib/postgresql/data
  ports:
   - 54322:5432
  environment:
   POSTGRES_PASSWORD: wimness
   
 web:
  image: lkc_web
  ports:
   - 8088:8080
  depends_on:
   - db
  links:
   - db

   
